### ISSUE TITLE
Contact form email is not working in nightly

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#961]
If a user fills the contact form on nightly.apinf.io and presses submit, the message never gets sent to the relevant email address specified in the settings form. If you try to enable the email in the settings form, the form complains about mailgun username and password.

To do: enable email in the settings, investigate what the form is expected for mailgun fields.

Also, check apinf.io settings as well.

Also, it would make sense to disable the contact form from landing page, if settings have not been provided.

**Comment by bajiat** [comment]
Check that the correction is also applied to settings wizard.

**Comment by frenchbread** [comment]
Contact form has been fixed in #970. Only check if settings are provided still needed.

**Comment by bajiat** [comment]
@frenchbread Thanks for clarification!

**Comment by brylie** [comment]
@frenchbread will you take this task?

**Comment by jykae** [comment]
Re-opening, because only partly fixed with #1070 

TODO: 
- check form validation
- mailgun settings are saved correctly
- and finally that the call for Mailgun succeeds.

![nayttokuva 2016-06-07 kello 16 53 48](https://cloud.githubusercontent.com/assets/293452/15860436/cb45ab44-2cd1-11e6-8bf9-7d06e0f4960f.png)

**Comment by jykae** [comment]
@frenchbread I try to look what is left in this, setup wizard accepted but when changing in settings page validation errors are still thrown when clicking Save button.

**Comment by brylie** [comment]
This is related to sub-field validation. In effect, we want the mailgun settings to be required if the feature is enabled, but not required otherwise. We have not figured out a simple way to do this.

**Comment by frenchbread** [comment]
@jykae OK, thanks

**Comment by brylie** [comment]
@frenchbread as a reference, we will probably need to do something similar to the following:

- SimpleSchema: [Make a field conditionally required](https://github.com/aldeed/meteor-simple-schema#make-a-field-conditionally-required)
